kind: pipeline
name: default
type: docker

steps:
  - name: app
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      username: cfu288
      PASSWORD:
        from_secret: registry_password
      repo: cfu288/mere-medical
      tags: latest

  - name: docs
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      username: cfu288
      PASSWORD:
        from_secret: registry_password
      dockerfile: Dockerfile-docs
      repo: cfu288/mere-medical-docs
      tags: latest

  - name: parallelize builds
    image: docker:dind
    commands:
      - echo "Done"
    depends_on:
      - app
      - docs

trigger:
  branch:
    - main
  event:
    exclude:
      - pull_request
