# Base image
FROM node:18

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json /app/

# Install app dependencies
RUN npm install

# Bundle app source
COPY . /app/

# Creates a "dist" folder with the production build
RUN npx nx build api

# Start the server using the production build
CMD [ "node", "dist/apps/api/main.js" ]
# CMD [ "ls", "dist/apps" ]
