FROM node:26.7.0-bookworm@sha256:e929171d35b9df7773a3ec5b068e387fa109441dc90f91e6560af5d39b7e9bf1 AS build-stage

WORKDIR /app
COPY package*.json /app/
RUN npm ci

COPY . /app/
ENV NX_DAEMON=false
RUN npx nx build docs

FROM nginxinc/nginx-unprivileged:1.30-alpine@sha256:44e36330f74d4f3a1d4e222acca9e23b401fb87811a7597024502bb759c4dd49

COPY --from=build-stage /app/apps/docs/build /usr/share/nginx/html
COPY --from=build-stage /app/default.conf /etc/nginx/conf.d/default.conf
