FROM node:26.7.0-bookworm@sha256:0353e48e0e8a993db87b720c242f54b207059d1bcc0106534896e8a11054c837 AS build-stage

WORKDIR /app
COPY package*.json /app/
RUN npm ci

COPY . /app/
ENV NX_DAEMON=false
RUN npx nx build docs

FROM nginxinc/nginx-unprivileged:1.31-alpine@sha256:901e944d1f4fc2bd077e8f5568b98c1f6f8cdacf6b97a87747c43134a339b9a7

COPY --from=build-stage /app/apps/docs/build /usr/share/nginx/html
COPY --from=build-stage /app/default.conf /etc/nginx/conf.d/default.conf
