FROM node:18 as build-stage

# Create app directory
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY . /app/
RUN npx nx build api:build:production  

# Base image
FROM node:18

WORKDIR /app
COPY --from=build-stage /app/dist/apps/api/ /app/
COPY --from=build-stage /app/node_modules/ /app/node_modules/
CMD [ "node", "main.js" ]
