name: Feature Request
description: Suggest a new feature or improvement
labels: ['Feature']
body:
  - type: markdown
    attributes:
      value: |
        > **Note:** This repository is managed by a single contributor who is a full time medical resident. I will attempt to respond to issues in a timely manner, however there may be weeks or months with slow responses.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why would this be useful? What problem does it solve?
    validations:
      required: false
