import { DatabaseSync } from 'node:sqlite';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { TENANT_DB_SCHEMA } from '@mere/tenant-db';

interface TableColumn {
  name: string;
  type: string;
  notnull: number;
  pk: number;
  dflt_value: string | null;
}

function pascal(name: string): string {
  return name
    .split('_')
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

function tsType(column: TableColumn, pkColumns: number): string {
  const bases: Record<string, string> = {
    INTEGER: 'number',
    REAL: 'number',
    TEXT: 'string',
  };
  const base = bases[column.type];
  if (!base) {
    throw new Error(`unsupported column type ${column.type} on ${column.name}`);
  }
  const rowidAlias =
    column.pk === 1 && pkColumns === 1 && column.type === 'INTEGER';
  const nullable = column.notnull === 0 && column.pk === 0 && !rowidAlias;
  const selected = nullable ? `${base} | null` : base;
  if (rowidAlias || column.dflt_value !== null) {
    return `Generated<${selected}>`;
  }
  return selected;
}

/**
 * Builds the Kysely schema source for one database by running its DDL against
 * an in-memory database and reading the resulting tables. FTS5 tables get their
 * declared columns as nullable text plus the rowid Kysely joins on.
 */
export function schemaSource(ddl: string[], databaseName: string): string {
  const db = new DatabaseSync(':memory:');
  try {
    for (const statements of ddl) {
      db.exec(statements);
    }
    return render(db, databaseName);
  } finally {
    db.close();
  }
}

function render(db: DatabaseSync, databaseName: string): string {
  const tables = db
    .prepare(
      `SELECT name, sql FROM sqlite_master
       WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
       ORDER BY name`,
    )
    .all() as unknown as { name: string; sql: string }[];
  const ftsNames = tables
    .filter((table) => table.sql.toLowerCase().includes('fts5'))
    .map((table) => table.name);
  const kept = tables.filter(
    (table) => !ftsNames.some((fts) => table.name.startsWith(`${fts}_`)),
  );

  const interfaces: string[] = [];
  const entries: string[] = [];
  let usesGenerated = false;
  for (const table of kept) {
    const columns = db
      .prepare(
        `SELECT name, type, "notnull", pk, dflt_value FROM pragma_table_info(?)`,
      )
      .all(table.name) as unknown as TableColumn[];
    const isFts = ftsNames.includes(table.name);
    const fields = isFts
      ? [
          '  rowid: number;',
          '  rank: number;',
          ...columns.map((c) => `  ${c.name}: string | null;`),
        ]
      : columns.map((column) => {
          const pkColumns = columns.filter((c) => c.pk > 0).length;
          const type = tsType(column, pkColumns);
          if (type.startsWith('Generated')) usesGenerated = true;
          return `  ${column.name}: ${type};`;
        });
    interfaces.push(
      `export interface ${pascal(table.name)}Table {\n${fields.join('\n')}\n}`,
    );
    entries.push(`  ${table.name}: ${pascal(table.name)}Table;`);
  }

  const importLine = usesGenerated
    ? `import type { Generated } from 'kysely';\n\n`
    : '';
  return (
    `// Generated by libs/emr-pipeline/src/db/generate-types.ts. Do not edit.\n` +
    importLine +
    interfaces.join('\n\n') +
    `\n\nexport interface ${databaseName} {\n${entries.join('\n')}\n}\n`
  );
}

const SQL_DIR = path.join(__dirname, 'sql');

export function warehouseSchemaSource(): string {
  return schemaSource(
    [
      fs.readFileSync(path.join(SQL_DIR, 'warehouse.sql'), 'utf8'),
      fs.readFileSync(path.join(SQL_DIR, 'staging.sql'), 'utf8'),
    ],
    'WarehouseDatabase',
  );
}

export function tenantDbSchemaSource(): string {
  return schemaSource([TENANT_DB_SCHEMA], 'TenantDatabase');
}

if (require.main === module) {
  fs.writeFileSync(
    path.join(__dirname, 'warehouse-schema.ts'),
    warehouseSchemaSource(),
  );
  fs.writeFileSync(
    path.resolve(__dirname, '../../../tenant-db/src/lib/tenant-db-schema.ts'),
    tenantDbSchemaSource(),
  );
  console.log('wrote warehouse-schema.ts and tenant-db-schema.ts');
}
